SUPABASE_API_URL=https://jfkhkwtbnkgpwzddybus.supabase.co
SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impma2hrd3RibmtncHd6ZGR5YnVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzI5MzgsImV4cCI6MjA2NDg0ODkzOH0.kFrXROJmpxYThfv3O8e7ohSMZATT7Cml_eHv2KHbjpU
